### ISSUE TITLE
Upgrade to z2jh 1.0

### ISSUE THREAD

**Issue by yuvipanda** [berkeley-dsep-infra/hubs#2427]
Zero to JupyterHub 1.0 has been released - https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/main/CHANGELOG.md#10.

We should upgrade to it!

**Comment by felder** [comment]
cs194 has the following error:
- prePuller.extraImages.postgres: Additional property policy is not allowed

Here's the offending snippit from cs194/config/common.yaml:
```
    extraImages:
      postgres:
        name: gcr.io/ucb-datahub-2018/jupyterhub-postgres
        tag: 0.0.1-n3657.h4f7f88c
        policy: IfNotPresent
```
@yuvipanda how should we deal with this `policy: IfNotPresent` config?
