### ISSUE TITLE
The idle culler is not working correctly

### ISSUE THREAD

**Issue by felder** [berkeley-dsep-infra/hubs#2452]
Looking at datahub-prod and as well data8x-prod, I see lots of pods with ages measuring in the multiple days.

For data8x-prod, in particular, there are hundreds of pods with ages measured in days.  For example:
```
kubectl -n data8x-prod get pods | tr -s ' ' | cut -d ' ' -f5 | grep d | wc -l
   464
```

This seems to me to be unusual or undesired behavior.  I see similar occurring in datahub, and I noticed this in the config for eecs:
https://github.com/berkeley-dsep-infra/datahub/blob/d75f71bfeb4ac55a8159bfe7e1af1468f894cc3b/deployments/eecs/config/common.yaml#L8

```
jupyterhub:
  cull:
    # For some reason, EECS hub users don't cull properly
    # Empty abandoned sessions stay on for days
    # This stops users after they have been running for 12+ hours
    # in one go. In several weeks of looking at user pods older
    # than this, none have been active.
    maxAge: 43200 # 12h
```

Is it possible this behavior is actually occurring across the board but went unnoticed?
