### ISSUE TITLE
Enable streaming image pulls for our hub user images

### ISSUE THREAD

**Issue by yuvipanda** [berkeley-dsep-infra/hubs#2958]
https://cloud.google.com/blog/products/containers-kubernetes/introducing-container-image-streaming-in-gke is a game changer, reducing image pull times from ~10min (as we have now) to something much, *much* smaller. Image Pull Time is one of the biggest components of new node spinup time for us, and drastically reducing that will have a huge impact on how we can scale. We can perhaps even remove our calendar based autoscaler!

TODO:

- [x] Enable Artifact Registry - streaming pulls are only supported from there
- [x] https://github.com/berkeley-dsep-infra/datahub/pull/2959
- [x] Fix permissions for our service account to push to artifact registry
- [x] Enable [Container Filesystem API](https://console.cloud.google.com/apis/api/containerfilesystem.googleapis.com/overview?project=ucb-datahub-2018)
- [x] Move node pools to the cos + containerd node image (we are now on cos + docker)
- [x] Enable streaming image pulls
- [x] Upgrade k8s master to be min supported version for this
- [x] Create new node pools after k8s master is new enough and streaming image pulls have been enabled

**Comment by yuvipanda** [comment]
I've just created new nodepools with cos-containerd as base image.

**Comment by yuvipanda** [comment]
Some continuous prepullers are being 'stuck' in beta nodes, with describe output like:

```
Events:
  Type     Reason                  Age   From                                   Message
  ----     ------                  ----  ----                                   -------
  Normal   Scheduled               19m   gke.io/optimize-utilization-scheduler  Successfully assigned biology-prod/continuous-image-puller-659bv to gke-fall-2019-user-beta-2021-11-04-4820cac2-84zg
  Warning  FailedCreatePodSandBox  19m   kubelet                                Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "c0068455027e861901fbc53e60ffcfe3ebe734e02943da2c1055ceb217317a08": stat /var/lib/calico/nodename: no such file or directory: check that the calico/node container is running and has mounted /var/lib/calico/
  Normal   Pulling                 19m   kubelet                                Pulling image "jupyterhub/k8s-network-tools:1.1.2"
  Normal   Pulled                  19m   kubelet                                Successfully pulled image "jupyterhub/k8s-network-tools:1.1.2" in 1.427235014s
  Normal   Created                 19m   kubelet                                Created container image-pull-metadata-block
  Normal   Started                 19m   kubelet                                Started container image-pull-metadata-block
  Normal   Pulling                 19m   kubelet                                Pulling image "gcr.io/ucb-datahub-2018/biology-user-image:23f5022"
  Normal   Pulled                  13m   kubelet                                Successfully pulled image "gcr.io/ucb-datahub-2018/biology-user-image:23f5022" in 5m35.111628977s
  Normal   Created                 12m   kubelet                                Created container image-pull-singleuser
  Normal   Started                 12m   kubelet                                Started container image-pull-singleuser
  Normal   Pulling                 12m   kubelet                                Pulling image "k8s.gcr.io/pause:3.5"
```

**Comment by yuvipanda** [comment]
beta pool kept failing continuous prepullers in this way, so I've deleted and recreated the nodepool. Other nodepools seem fine?

**Comment by yuvipanda** [comment]
Well, I think I've ticked all the boxes but I don't see the images being streamed yet.

**Comment by yuvipanda** [comment]
I don't see the `gcfsd` process mentioned in https://cloud.google.com/kubernetes-engine/docs/how-to/image-streaming#troubleshooting in the nodes. I wonder if I need to bump up versions. I'll just upgrade things tomorrow and see if it gets it to work.

**Comment by yuvipanda** [comment]
I upgraded k8s cluster master, but no dice still. I don't see any specific processes around this on the nodes either, nor anything in the containerd config:

```toml
yuvipanda@gke-fall-2019-user-delta-2021-11-04-048be50f-v3tt ~ $ cat /etc/containerd/config.toml 
# Kubernetes doesn't use containerd restart manager.
disabled_plugins = ["restart"]
oom_score = -999

[debug]
  level = "info"

[grpc]
  gid = 412

[plugins.cri]
  stream_server_address = "127.0.0.1"
  max_container_log_line_size = 262144
[plugins.cri.cni]
  bin_dir = "/home/kubernetes/bin"
  conf_dir = "/etc/cni/net.d"
  conf_template = ""
[plugins.cri.registry.mirrors."docker.io"]
  endpoint = ["https://mirror.gcr.io","https://registry-1.docker.io"]
```

**Comment by yuvipanda** [comment]
My next step is to upgrade to k8s 1.20 (today we just got upto 1.19). The hope is that by having already turned on image streaming (as we have) before creating new nodepools, they will be enabled properly.

**Comment by yuvipanda** [comment]
I created a new nodepool (to deal with #2966), and here is the config on that:

```toml
# Kubernetes doesn't use containerd restart manager.
disabled_plugins = ["restart"]
oom_score = -999

[debug]
  level = "info"

[grpc]
  gid = 412

[plugins.cri]
  stream_server_address = "127.0.0.1"
  max_container_log_line_size = 262144
[plugins.cri.cni]
  bin_dir = "/home/kubernetes/bin"
  conf_dir = "/etc/cni/net.d"
  conf_template = ""
[plugins.cri.registry.mirrors."docker.io"]
  endpoint = ["https://mirror.gcr.io","https://registry-1.docker.io"]
[plugins.cri.containerd]
  snapshotter = "gcfs"
  disable_snapshot_annotations = false
[proxy_plugins]
  [proxy_plugins.gcfs]
    type = "snapshot"
    address = "/run/containerd-gcfs-grpc/containerd-gcfs-grpc.sock"
```


I can see a snapshot plugin!

I also see a `gcfsd` process! YAY.

So it looks like your k8s master version needs to match the minimum requirement, and it isn't enabled on existing nodepools (or just existing nodes?)
