### ISSUE TITLE
New data8x hub cannot get SSL Cert

### ISSUE THREAD

**Issue by felder** [berkeley-dsep-infra/hubs#3259]
### Bug description

@sean-morris has requested a new data8x hub so that he can migrate people from the old grader to the new.

To do this, in my forked datahub repo I have copied data8x to data8xv2.  I've then adjusted the hubploy configs to instruct data8xv2 to use data8x's image, configured the proxy to use staging-hubv2.data8x.berkeley.edu, and added DNS entries for it in infoblox.

When I use hubploy to deploy it, I see the following error from the autohttps pod :

```
kubectl -n data8xv2-staging logs autohttps-86ddd98585-sxb7b traefik
...
time="2022-02-15T02:42:55Z" level=error msg="Unable to obtain ACME certificate for domains \"staging-hubv2.data8x.berkeley.edu\" : unable to generate a certificate for the domains [staging-hubv2.data8x.berkeley.edu]: error: one or more domains had a problem:\n[staging-hubv2.data8x.berkeley.edu] acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: Invalid response from http://staging-hubv2.data8x.berkeley.edu/.well-known/acme-challenge/REMOVED [104.198.75.230]: 404\n" providerName=default.acme
```

### Environment & setup

- Hub: data8x
- Project: data8x-scratch
- Cluster: data8x-2019-02-20

### How to reproduce

See description.

**Comment by felder** [comment]
@yuvipanda @ryanlovett any ideas?

Ryan mentioned he had seen this error before when spinning up new hubs but that after a time the error would go away if the hub was redeployed or the proxy pods were killed.  Unfortunately, in this case the error persists.

**Comment by ryanlovett** [comment]
@felder We had seen similar errors several years ago when spinning up new hubs, but I don't know if it was this one specifically.

You might try debugging by going into whatever pod holds the acme-challenge data and see what is there. It is saying `/.well-known/acme-challenge/REMOVED` is 404, but what is available?

**Comment by felder** [comment]
@ryanlovett My investigations on the pod seem to suggest it's accessing an account created by yuvi:

```
/etc/traefik/..2022_02_15_02_41_29.216960744 $ cat traefik.yaml
accessLog:
  fields:
    headers:
      names:
        Authorization: redacted
        Cookie: redacted
        Set-Cookie: redacted
        X-Xsrftoken: redacted
  filters:
    statusCodes:
    - 500-599
certificatesResolvers:
  default:
    acme:
      caServer: https://acme-v02.api.letsencrypt.org/directory
      email: yuvipanda@berkeley.edu
      httpChallenge:
        entryPoint: http
      storage: /etc/acme/acme.json
entryPoints:
  http:
    address: :8080
  https:
    address: :8443
    transport:
      respondingTimeouts:
        idleTimeout: 10m0s
log:
  level: WARN
providers:
  file:
    filename: /etc/traefik/dynamic.yaml
```

```
/etc/acme $ cat acme.json
{
  "default": {
    "Account": {
      "Email": "yuvipanda@berkeley.edu",
      "Registration": {
        "body": {
          "status": "valid",
          "contact": [
            "mailto:yuvipanda@berkeley.edu"
          ]
        },
        "uri": "https://acme-v02.api.letsencrypt.org/acme/acct/409534860"
      },
      "PrivateKey": "REMOVED",
      "KeyType": "4096"
    },
    "Certificates": null
  }
}
```

I wonder if perhaps letsencrypt needs to be informed of domains it is providing certs for.
