### ISSUE TITLE
Bump repo2docker version in CI

### ISSUE THREAD

**Issue by ryanlovett** [berkeley-dsep-infra/hubs#4275]
### Bug description

Our .circleci/config.yml pins https://github.com/jupyterhub/repo2docker/commit/968cc43a9e238916b5032edbf84e309c8d4ff35e which is from 11/11/2020. This is somewhat stale and causes our user images to ship with a lot of old dependencies. @fperez needs newer npm in stat159 for example. It is also based on Ubuntu Bionic 18.04 which will [stop being supported](https://wiki.ubuntu.com/Releases) _this semester_!

We should consider bumping up this version in the pre-term maintenance windows to ensure our images have updated packages. It looks like repo2docker tends to release a couple of times a year.

I did try to update repo2docker during the maintenance window in Dec. 2022, but it [broke something](https://github.com/berkeley-dsep-infra/datahub/commit/157f650427f29c22fd3ec8570c077483cb7f80c1) in a11y's image so I reverted. a11y uses an alpha version of notebook 7 and that issue is probably already resolved with recent notebook 7 commit.

Lastly, I'm not sure why but we also install repo2docker inside some singleuser environments. I think this is only useful if you wanted to build images inside user sessions on hubs (see below), but I don't know of anyone who does that.
```
deployments/a11y/image/environment.yml
deployments/data100/image/environment.yml
deployments/stat159/image/environment.yml
```

### Environment & setup

- Hub: all

### How to reproduce

.

**Comment by ryanlovett** [comment]
In a local environment I was able to bump repo2docker to a version that supports specifying the base image, `repo2docker --Repo2Docker.base_image=buildpack-deps:jammy .`. In our CI, repo2docker actually runs via a library call from within hubploy. We would need to alter hubploy to pass the `base_image` parameter on to r2d.

repo2docker is able to build and run several images successfully. When I tried running the desktop in the cee image, only a black screen was displayed. I could invoke `DISPLAY=:1 xfce4-terminal` from a jupyter terminal and that would cause a window to render in the noVNC tab, but it could not actually run a shell. So there is a possibility that some images are currently incompatible with jammy or we may need time to fix them.

Right now, all images use the same repo2docker invocation. Until issues like the above are resolved, we would have to be able to tell hubploy to use jammy for some images and bionic for others. Putting this configuration in each deployment's `hubploy.yml` makes sense, but this would need more development time.

**Comment by ryanlovett** [comment]
I forgot that cee is not actually enabled so I repeated the process for data100. This time I did [patch hubploy](https://github.com/berkeley-dsep-infra/hubploy/compare/r2d-base-image) so that when I modified data100's hubploy.yaml:
```yaml
images:
  images:
    - name: us-central1-docker.pkg.dev/ucb-datahub-2018/user-images/data100-user-image
      path: image/
      repo2docker:
        base_image: docker.io/library/buildpack-deps:jammy
  registry:
    provider: gcloud
    gcloud:
      project: ucb-datahub-2018
      service_key: gcr-key.json

cluster:
  provider: gcloud
  gcloud:
    project: ucb-datahub-2018
    service_key: gke-key.json
    cluster: fall-2019
    zone: us-central1
```

hubploy passed along the base_image parameter to repo2docker, and the modified repo2docker (Yuvi's PR, 909) built the image as specified.

The desktop proxy actually worked just fine too, so that was a red herring with the locally running cee image.
