### ISSUE TITLE
RStudio not inheriting gh-scoped-creds env vars

### ISSUE THREAD

**Issue by ryanlovett** [berkeley-dsep-infra/hubs#5551]
_Originally posted by @cboettig in https://github.com/berkeley-dsep-infra/datahub/issues/5515#issuecomment-1947775552_
> @balajialg ah, ok we did discover one wrinkle here.  When students are using the RStudio interface, the `GH_SCOPED_CREDS_CLIENT_ID` environmental variable and `GH_SCOPED_CREDS_APP_URL` aren't visible on the terminal or the R session because RStudio insists on ignoring global env vars unless they are echoed into Renviron (e.g. into `$R_HOME/etc/Renviron.site`).  Is there a way to do this?

**Comment by ryanlovett** [comment]
Here is one general approach without making it specific to gh-scoped-creds:

1. Create a configmap from the gh-scoped-creds vars
2. Mount the configmap into the singleuser pod at somewhere like /etc/Renviron.site.d/gh-scoped-creds.env
3. In Renviron.site, run something like:
```
# Get a list of files in the directory
env_dir <- "/etc/Renviron.site.d/"
env_files <- list.files(env_dir, full.names = TRUE)

# Iterate over each file
for (env_file in env_files) {
    cat("Loading environment variables from:", env_file, "\n")
    
    # Read and parse the environment file
    readRenviron(env_file)
}

```
This is code in Renviron.site, but it doesn't violate the spirit of the file I think. This way we could add any number of different env vars without having to alter the setup code each time.

I'll think about it a little more though. The configmap would be redundant with the extra env vars, so maybe there's a way to consolidate.

**Comment by ryanlovett** [comment]
More spitballing...

In hub/templates/gh-scoped-creds.yaml we'd have:
```yaml
{{ if .Values.ghScopedCreds.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: gh-scoped-creds
data:
  GH_SCOPED_CREDS_CLIENT_ID: {{ .Values.ghScopedCreds.clientID | quote }}
  GH_SCOPED_CREDS_APP_URL: {{ .Values.ghScopedCreds.appURL  | quote }}
{{ end }}
```

This is similar to how we define NFS server config per hub.

We'd set the default in hub/values.yaml:
```yaml
ghScopedCreds:
  enabled: false
```

And we'd prepare hub-specific config at deployments/_deployment_name_/config/common.yaml:
```yaml
ghScopedCreds:
  enabled: true
  clientID: ...client ID...
  appURL: ...app url...
```

Then in singleuser.extraEnv we'd export the configmap as env vars:
```yaml
    - name: GH_SCOPED_CREDS_CLIENT_ID
      valueFrom:
        configMapKeyRef:
          name: gh-scoped-creds
          key: GH_SCOPED_CREDS_CLIENT_ID
    - name: GH_SCOPED_CREDS_APP_URL
      valueFrom:
        configMapKeyRef:
          name: gh-scoped-creds
          key: GH_SCOPED_CREDS_APP_URL
```

And in singleuser we make the configmap available as a file:
```yaml
  extraVolumes:
    - name: gh-scoped-creds
      configMap:
        name: gh-scoped-creds
  extraVolumeMounts:
    - name: gh-scoped-creds
      mountPath: /etc/R/Renviron.d/gh-scoped-creds.env
      subPath: gh-scoped-creds.env
      readOnly: true
```

This lets us set the gh-scoped-creds key/values _once_ in per-deployment config, and it will both export them in the environment, and make the vars available via file for RStudio to pick up. All at the expense of more yaml up front. The alternative is to add the env vars within files to the singleuser image, which involves rebuilds for small changes.

I wonder if we can sweep up the latter two sections above into the template or in some other conditional way, since they'd be boilerplate whenever ghScopedCreds is enabled.

@shaneknapp Thoughts? I'll test this with manual hubploys before I make a PR since I've never created a template before. I'll need to modify /etc/R/Renviron.site with a separate PR as described above.

@balajialg Once I'm confident that the env vars are being passed to RStudio correctly, I'll make a PR that defines the variables for dlab.

**Comment by ryanlovett** [comment]
> The alternative is to add the env vars within files to the singleuser image, which involves rebuilds for small changes.

Another alternative is to use [singleuser.extraFiles](https://z2jh.jupyter.org/en/stable/resources/reference.html#singleuser-extrafiles). This is simpler, but we'd have to set the variables twice: once in extraEnv and once in extraFiles. (along with the code addition to Renviron.site)

```yaml
singleuser:
  extraFiles:
    gh-scoped-creds:
      mountPath: /etc/R/Renviron.d/gh-scoped-creds.r
      stringData: |
        GH_SCOPED_CREDS_APP_URL=...
        GH_SCOPED_CREDS_CLIENT_ID=...
      mode: 0644
```

I have a feeling this is the right choice, although the configmap method would be interesting if it could be streamlined.
