### ISSUE TITLE
Restore table of contents on documentation landing pages

### ISSUE THREAD

**Issue by ryanlovett** [berkeley-dsep-infra/hubs#5949]
# Summary

The old .rst site had landing pages for major sections containing a sub table of contents for those sections. Quarto does not support this natively, but it may be possible to move the main TOC from `_quarto.yml` to a separate YAML file, and then reference that in `_quarto.yml` and in an [EJS template](https://ejs.co/) that [populates](https://quarto.org/docs/websites/website-listings-custom.html) the sub TOCs.

I imagine a landing page could have:
```yaml
title: "Some Landing Page"
listing:
  - id: toc
    template: assets/toc.ejs
    contents: _toc.yml

## Table of Contents

This section's pages:

::: {#toc}
:::
```

I'm not sure how to reference a section within the main `_toc.yml` from this listing and template, but I haven't looked into it.
